# Generated by Django 5.1.7 on 2025-03-20 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("wax", "Wax"),
                            ("wick", "Wick"),
                            ("fragrance_oil", "Fragrance Oil"),
                            ("dye", "Dye"),
                            ("mold", "Mold"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_in_stock", models.PositiveIntegerField()),
                ("reorder_level", models.PositiveIntegerField(default=10)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.supplier",
                    ),
                ),
            ],
        ),
    ]
