# Generated by Django 5.1.7 on 2025-03-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_supplier_rawmaterial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rawmaterial",
            old_name="quantity_in_stock",
            new_name="quantity",
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.supplier",
            ),
        ),
    ]
