# Generated by Django 5.1.7 on 2025-03-20 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0003_rename_quantity_in_stock_rawmaterial_quantity_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="rawmaterial",
            old_name="quantity",
            new_name="quantity_in_stock",
        ),
    ]
