# Generated by Django 5.1.7 on 2025-03-20 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_finishedgoods_stockalert"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_name", models.CharField(max_length=255)),
                ("batch_size", models.IntegerField()),
                ("time_taken", models.DurationField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workers_assigned",
                    models.ManyToManyField(
                        related_name="production_batches", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
