# Generated by Django 5.1.7 on 2025-03-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("hours_studied", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="ProgressTracking",
        ),
    ]
